Repository CS3450-Group9/Dans-AutoBarn, pull requests merged in 2023-02, with the labels that each got.

#15 Updated .gitignore
  web/.gitignore
Labels: bug

#16 updated the docs to include sprint retrospectives and standup meeting notes
  docs/SprintRetrospectives.md
  docs/Standups.md
  docs/referencePhotos/burndownUpdates/README.md
  docs/referencePhotos/kanbanUpdates/README.md
Labels: documentation

#17 Updated for standup & sprint retrospective
  README.md
  docs/SprintRetrospectives.md
  docs/Standups.md
  docs/referencePhotos/burndownUpdates/02-03-23.png
  docs/referencePhotos/burndownUpdates/README.md
  docs/referencePhotos/kanbanUpdates/02-03-23.png
  docs/referencePhotos/kanbanUpdates/README.md
Labels: documentation

#19 G9 18 user class diagram
  docs/classUMLs/README.md
  docs/classUMLs/figs/UserClass.png
Labels: documentation

#20 Authentication activity diagram made. Updated readme.
  docs/activityDiagrams/README.md
  docs/activityDiagrams/figs/Authentication.png
Labels: documentation

#22 Low-Fidelity prototype drafted, with README
  docs/prototypes/README.md
  docs/prototypes/figs/SearchForCar.png
Labels: documentation

#23 G9 17 login page interface w db
  README.md
  web/.gitignore
  web/DansAutoBarn/settings.py
  web/DansAutoBarn/urls.py
  web/UserAuth/__init__.py
  web/UserAuth/admin.py
  web/UserAuth/apps.py
  web/UserAuth/forms.py
  web/UserAuth/migrations/0001_initial.py
  web/UserAuth/migrations/__init__.py
  web/UserAuth/models.py
  web/UserAuth/static/UserAuth/component.js
  web/UserAuth/static/UserAuth/style.css
  web/UserAuth/templates/UserAuth/base.html
  web/UserAuth/templates/UserAuth/home.html
  web/UserAuth/templates/registration/login.html
  web/UserAuth/templates/registration/signup.html
  web/UserAuth/tests.py
  web/UserAuth/urls.py
  web/UserAuth/views.py
Labels: enhancement

#25 G9 19 car class diagram
  docs/classUMLs/README.md
  docs/classUMLs/figs/CarAndReservationClass.png
Labels: documentation

#26 Created migration files
  web/UserAuth/migrations/0001_initial.py
  web/UserAuth/migrations/0002_populate.py
  web/UserAuth/models.py
  web/UserAuth/templates/UserAuth/base.html
  web/UserAuth/templates/UserAuth/home.html
Labels: enhancement

#27 added reservation diagram
  docs/activityDiagrams/README.md
  docs/activityDiagrams/figs/Reservation.png
Labels: documentation

#24 Origin/g9 12 basics views for authenticated users
  prototypes/Checkout-incar.jpg
  prototypes/Customer Dashboard.jpg
  prototypes/Customer searches for a car activity diagram.jpg
  prototypes/Employee Dashboard.jpg
  prototypes/Manager Dashboard.jpg
Labels: documentation

#29 Documentation
  docs/GroupMeetingNotes.md
  docs/README.md
  docs/SprintRetrospectives.md
  docs/Standups.md
  docs/referencePhotos/burndownUpdates/02-06-23.png
  docs/referencePhotos/burndownUpdates/02-08-23.png
  docs/referencePhotos/burndownUpdates/02-10-23.png
  docs/referencePhotos/burndownUpdates/02-13-23.png
  docs/referencePhotos/kanbanUpdates/02-06-23.png
  docs/referencePhotos/kanbanUpdates/02-08-23.png
  docs/referencePhotos/kanbanUpdates/02-10-23.png
  docs/referencePhotos/kanbanUpdates/02-13-23.png
Labels: documentation

#30 moved prototypes, updated readme
  docs/prototypes/README.md
  docs/prototypes/figs/CheckoutCar.jpg
  docs/prototypes/figs/CustomerDashboard.jpg
  docs/prototypes/figs/EmployeeDashboard.jpg
  docs/prototypes/figs/ManagerDashboard.jpg
  prototypes/Customer searches for a car activity diagram.jpg
Labels: bug

#31 Milestone_2
  README.md
  docs/GroupMeetingNotes.md
  docs/README.md
  docs/SprintRetrospectives.md
  docs/Standups.md
  docs/activityDiagrams/README.md
  docs/activityDiagrams/figs/Authentication.png
  docs/activityDiagrams/figs/Reservation.png
  docs/activityDiagrams/figs/addBalance.png
  docs/classUMLs/README.md
  docs/classUMLs/figs/CarAndReservationClass.png
  docs/classUMLs/figs/UserClass.png
  docs/prototypes/README.md
  docs/prototypes/figs/CheckoutCar.jpg
  docs/prototypes/figs/CustomerDashboard.jpg
  docs/prototypes/figs/EmployeeDashboard.jpg
  docs/prototypes/figs/ManagerDashboard.jpg
  docs/prototypes/figs/SearchForCar.png
  docs/referencePhotos/burndownUpdates/02-03-23.png
  docs/referencePhotos/burndownUpdates/02-06-23.png
  docs/referencePhotos/burndownUpdates/02-08-23.png
  docs/referencePhotos/burndownUpdates/02-10-23.png
  docs/referencePhotos/burndownUpdates/02-13-23.png
  docs/referencePhotos/burndownUpdates/README.md
  docs/referencePhotos/kanbanUpdates/02-03-23.png
  docs/referencePhotos/kanbanUpdates/02-06-23.png
  docs/referencePhotos/kanbanUpdates/02-08-23.png
  docs/referencePhotos/kanbanUpdates/02-10-23.png
  docs/referencePhotos/kanbanUpdates/02-13-23.png
  docs/referencePhotos/kanbanUpdates/README.md
  web/.gitignore
  web/DansAutoBarn/settings.py
  web/DansAutoBarn/urls.py
  web/UserAuth/__init__.py
  web/UserAuth/admin.py
  web/UserAuth/apps.py
  web/UserAuth/forms.py
  web/UserAuth/migrations/0001_initial.py
  web/UserAuth/migrations/0002_populate.py
  web/UserAuth/migrations/__init__.py
  web/UserAuth/models.py
  web/UserAuth/static/UserAuth/component.js
  web/UserAuth/static/UserAuth/style.css
  web/UserAuth/templates/UserAuth/base.html
  web/UserAuth/templates/UserAuth/home.html
  web/UserAuth/templates/registration/login.html
  web/UserAuth/templates/registration/signup.html
  web/UserAuth/tests.py
  web/UserAuth/urls.py
  web/UserAuth/views.py
Labels: documentation, enhancement

#33 G9 32 create landing home page
  docs/SprintPlanning.md
  docs/SprintRetrospectives.md
  web/DansAutoBarn/settings.py
  web/UserAuth/static/UserAuth/media/carVending.jpg
  web/UserAuth/static/UserAuth/media/testarossa.jpg
  web/UserAuth/templates/UserAuth/home.html
  web/UserAuth/templates/registration/login.html
  web/UserAuth/templates/registration/signup.html
  web/static/component.js
  web/static/style.css
  web/templates/base.html
Labels: enhancement
